[Search]
  SearchDescription = false
  MaxResults = 10

[UI]
  TitleFontFile = "Fonts/CascadiaCode-SemiBold.ttf"
  TitleFontSize = 66
  MainFontFile = "Fonts/CascadiaCode-SemiLight.ttf"
  MainFontSize = 22

[[Rules]]
  Match = "C"
  Description = "Open C:\\"
  Exe = "explorer.exe"
  Args = ["C:\\"]

[[Rules]]
  Match = "GH"
  Description = "Open github.com"
  Exe = "firefox.exe"
  Args = ["https://github.com/"]

[[Rules]]
  Match = "ex1"
  Description = "Example rule 1"
  Exe = "dummy.exe"
  Args = ["arg 1"]

[[Rules]]
  Match = "ex2"
  Description = "Example rule 2"
  Exe = "dummy.exe"
  Args = ["arg 1", "arg 2"]

[[Rules]]
  Match = "ex3"
  Description = "Example rule 3"
  Exe = "dummy.exe"
  Args = []

[[Rules]]
  Match = "ex_noargs"
  Description = "Example rule (no args)"
  Exe = "dummy.exe"

[[Rules]]
  Match = "accents"
  Description = "àâä éèêë ìîï òôö ùûü ÿ"
  Exe = "dummy.exe"
